language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  api_key:
    secure: jDdQJCPGPBrZDRco7ar6dWrS6UaF1wIPkc37JO3cE5C3PD0x/Ci5TZ3FlLdCs0Q7/k3v+VihOdCKQF2TeEbAlsiJoeKXKjLz5nrQTFNz811FnC6oNL321XlV48QixO8dTa7BXZk6FnoHLAWwT+bBa0dDWeZ4RQ5equKPAyL1wE1xWPWL/y9qlayo+cXlkx4ooZHEAcjiw9jVKC2PYIoVae6DEBPRhoFZMtt4PjDd7wNRIptmCWUJpNfADA0Mr7WFyh495H/7y9O0rcaW2BrNlHmf0vS41TvUJt2XQfjfbGbhBz1iBVWDrl0nfC/oyf5m2h+KFWqPZvDKt90LbyEOZMV6kakcohdK181yHgYTJ4loFXY4ryNXt0pOnU/lZsWZ1JeJ/yY3Sdm0k+Zb6Az16/YLeu65ub8RK+Yc+6mG/jKHXysLrM0yqcYdYrkEeKq4Z4Ld7R93BaF2bCv+15eQoMlejA807GOEu7lN/MbKTpnGw2BzbDDGUCWqb8qDXQjaQVmwQq8MaVwRVBbrgMNlJKR1uNVxvLrj77Ryak8D8k+ItWbQIjZgvN2fd/AO/bKXPleKCr1pQeoSLk4kM0UQmRxtExJKDx/vdsrsNJ1BwZtKfOMLUOrGabYQTemnNlyyy36bFaGHw33usrK4FtXUaSKqoer4E1ErKviEcXPVpI0=
app: josenvisa
true:
  repo: peeveepv/Quiz
  branch: master
