language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  api_key:
    secure: YNocQm7q4Yvv66RwW/OmcqEtrSC4uBBG+QPbufmlci+c2Ohcofhzm/AngBxPu3+8LApwtVfUK/DxmkyVmb+YvsLrVIexH7laIt7KaQ+EY+3gfIWU3z9FOXI+WzU1IXg28hr668XbnmEzoYVKQxsHV6tviSTLBoIet83MYZKZpRw2Bgpj6i4kd2jBp9ue7kpredYUiQHdjkALiVZ9Pgq7Mo24x3K10WaQB7lD0gKdFUFy1jErB7wQg6MPab2py1AgIYoZyTdp53RFBTUV876zGNGY0iPFHoauli0+7V/ZJ2CkctD3fOyocOf4MWiZXP/VKca25WyHej0LZDcmIEwxwMYNwLKVgIByJVMw/hubJqCRpCkHBoB5jRjqP9DnMseaX+ZyL9nICuro5ChZNL/DCruq44WDtG+iY2VyyTXvL0pqoiPnYx43wQ6DtM6p1S3sFiiUPQ/R3N+LZ67pGdAqaXfPRp+QIlb5jjaLeMDG9oDz2Zo5ABhcXdPCxu3uZ5f+Z1dlVAi272blPcnhWRa9rE/o8NmY2bRey4Olh67Wt6ePBLQzUHP7Wen5BQWRhUHj2Ru2KT9sDb5uXs0xefTHtKzEFMewpI9VT0BfJqr22yYM3QXtHVrPKaYq/qZ5OkESY91R5FYxmBkxNu9idoDuZ3kVDIIFfRmxpTuyLD3onkA=
app: josenvisa
true: 
repo: peeveepv/Quiz
