language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: nV7PmlICSIWpAQ16UVIxyvzY6Jk9a6k0TjaYGKDc61zuSNWBP9Tx4PYaWrUYlOrrdw6earsolBPuK/KTkIVvRPC9qWHMdXkpMrPFDIEw6PoW8FUjbjg7an29ZbyQhjDqduqlY/6A7LP5uTLTWp7thSYFxrVlaxyFeHXOS5Bih9f0lHJTqbbekk+AwIHLOrK3uRrY3Wm0c/gEmeERn2Kh2kYvh5vuYHC8A6lny5JD8J2LG0Whck719aCTkhYaOdm/POmignRb3/QruJ4lTfasLKISQtBTR9jgeFvRtvtVSyOagic/Vbgbzl1VETjSXGvN/u1NCCWcVykDtk8ySvODvQONypdu2zUyrpz2CBHi3suR2fF370DCANyXcdkAqcSZSvn1FDhqp7nvDTzLwAk3TAzolY97Gvv0zzkB07p4mccZwu+NB6k20gF7Ix2gt2EbqlMGLjtQLHGjR6bFp8qb4vPsK6tejZC3TZcH2eHkgNv0lvlGykV/bBH71x7/TNUY/DCBueLHtl5GR3ArB4BQdLpDYLwh5XMVcABNMRHbbOMI1etasHNV8j6XaJ0SE4sHMg4Jmxkyl907X7P5ygS53e/ejlgeVts+9rMVyHEX5MmhloT2KVIgbONNIh/AjKpWRqHQWycc2/ZZce/F35hvhDsBLoEr4taLTj6ZhA5DrrQ=
app: visapeli
true:
  repo: peeveepv/Quiz
