language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  api_key:
    secure: VTGFEWQJ/B5664TceccEqqlsCLm0Hm5HOpzDamddYdzCvnS+ph09R4hdoAc/Cxt26faGvRGuiu3xlfMfu0g974Zf6x2kWkP48sqr4pCBTCk0SQY6vrfE/FGFYJ38tFduz3P3j4eeqDkua+huHXLZ3ioMYEq7uCWLlqt1RnmbWAGG3vAqK2+SVBXXuyWLeTjyVhu110GHXDXJH8wJWH2hxEEOk5V+/ejmSUzonkmvaQL0P3AiZyxgFejHUZOjr6wyHNaM5I1/547lKvPZ1E35VWy2D4DT90AjJZcdIgYHGUJrN/iydwFQzZXDytzNCyffsZKt6kxzxwRsRBG6HecTpjfVX+zH8ceZKuVOBdD80b/npiZxRbWOmIaVKujdYEP/KxNvGB9BsWsjSiH7H31YigfPEIXDaTlUUktX4we5I4xs9GSRk77sJLjiz8nznUwbjFdG94gTU8VtgkHsJTXp6WuL9cH0myBCTyvFKxlRV6Qu9ErFUYLQU1214ApaRlWCWijniMRj+jTBEJLOo53t3vZFKXz3Tt6MIdX9gfmr290Xpxq8LHVQ3vHGujTL6/k5lsCRsAHydTRkZ3Pjrbomun9P/ZI+DuE3kCOE9R5e0rDIWzLbEPVgQxe258Or+yXLPhoaXnKDnVOc9AlorYlQINgBtMX1HVWnqUncmev2Ejk=
app: josenvisa
true:
  repo: peeveepv/Quiz
  branch: master
