language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  api_key:
    secure: LzYSrzUXCTcTFkRiTk6KV1SDKk2g6qlx+pV8s3Ncgf+lOWXWYtXOmINdlDGQXveKbqpvceM6G5kZ2hcE0d7soIu1ztv0gIQroyAWFXlF3cCwXsyQ4M8R9KSnVGyrVkdLym+x8IVwIV8JtznaUARL44Z9PHOtkS2paufmbdlga+qR7l0Vzs1EavpHs4rPiOLMb9VLDAGTxOKT0l3zl8SlXzsqzrmLLPABoWmcVYvc40Dqbg1ymPYij4Oh0SRr8C53wSGJbA2828YKAdRIujc1ZlWdFhG20wqa2bz+CcNOqTl/+qEAG0tWy7ZGW2UO7LcaWfTAl2IwgZA+VZ0O/fd+zNkJgifbje+mBtMPzntU3uKJvLmLvCTALerkKb5cjbih9OV50bZtoo1LBx3ExyOccs1H+g+yDhmt/4kG7SXTdsUYeQOe/uJSnMEKqhyseEK2RGdRK4P7ysSEf0EU64pxxlpd9sQipcncbHqhQrPmyB7uG8sFAsQM13UAWU+OT6T+9txB73icyrJAc3RLYZO2+WrTe6cFhr1ToWGzojg3FH9W5CctklX3chtO5mlIt9iEyCg6c7ALyN2JPNfAnk69gaiM30l59N6JHWpbnS0LFf5sUqw814vU7XlZzduZvr/kYPs1ZUcbnHVco7WX0Sphvj8NTUg6+MzS++P7b6yTDnw=
app: josenvisa
true:
  repo: peeveepv/Quiz
  branch: master
