language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  api_key:
    secure: Q+F/vKyWVOyNdTJbEqt9OpWv4XaGFOS4th4nmEdNVf2S9pnHlX1j2ZkGbaG8/kugc1Cfme2INv9csU/KzM4XdNuCBv8kwV8TGjk/zNQKgIkjgUVM/9JT78HBNC/c0++H7j5LX0nGTFk8gohnqpPgXYPxKqQLj1+qou6IhDlDVD51QZF/6RR7+2tqmdj4PI8xCVVcgf3jb2PxVC3cQhXlGpY9XcQaZdCejImkw1+hPbFIsemhTwMiaIKx7daKNkq3963qWJPntb4zQo9eXF2PuXAJKdm+q14AKdPwFf/GIqJNd2tTkQ5v7vZXrL5f+QwXW7LmVJV7fqE/LIW+8Y0fK2YZPoKG6OmxdVg2kuVJQ80/gEZDw99iDZo+eRRGk2F535RKJpbqOzfLeXjJob+06ZL+KbC3VPQIGqnUfklhJXnv/KH1J2IKm5eZWc4YsK5kAIpWUrKBMBiwjX13b7dDXpbOyFcaaEsa4rHU0tBFjt4Inmy5aY4imSI86HuxbDAWJ0COhIMeH876XVcShW8UC9VSMpHpUgnsCMJMHWJ8mApJL4GgAtQ8IcWti5aeTFOdSwLUwcCk88g8uLL31NtORzHeqvq1RDrnkNvORmdrnS93IZKND63HArKgX3651+zYSTcdNm035kY5kUeyzyG/NF2lu1GvkupALj2oAJjChTk=
  app: visapeli
  on:
    repo: peeveepv/Quiz
