language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  api_key:
    secure: HluvxjcseEopoXuxZwKNkEXPdGtGG/YAbdc0eOc28p2++7tTYngv310+EFnoEKms7U1v3eFq4tV3KVHflbR8IGmeiAPEFDLUgEp6ynKHzc/6s6A9zdzVhnpV0ygO6pHwd5xV13VQFxH9sy+YH+PpdzAfCySijn52QyqPu623Do6nKokq7dGJRW7sst9mybcaMJQiymtlu8jxJYYWAG90GCIEu2dOy/B0IrKPEqPhxHpXVK5SPNumN8y11P7zovPNMqtTKosYZrNCKA/2Ph/UCYBHF1/xzPmO2hbI0uSh7/9iTVsKCwc2NvJmqlT5TSOCMVHEhuNPvzpUlhoMK22b7ZPedQ3XwgLLfYMk97ZIiEdMt3laLXpSG5pkqTOgzsg6ZRCmoYX67YGBSHIR69DC2CgwhyLhqRCzKO0kBgaZF/GoxeGa4wBLrFCOkkIZZHfZ+gO4LkWrbD0YplEPLoHcpKf9Fegpx/MglZuAahgV+cxTLRjYLCgcLBRL2IRJjbALCfcj3Hw8vXQHky0pTcd6ZmMwyKDpQ3SNjQxqndXawAan/nEkY2xbf5HfBUq91a2tVDe0IXgH3pLcRIWa29nOjQHXRj7KVYcPOA4WNAj/TdBm0B6eV6q9X+/fVxrSxEkSPaDkd+hIaKjndvLyclnKqHItUq+R7GXE03Ylj1WxP/I=
app: josenvisa
true:
  repo: peeveepv/Quiz
  branch: master
