language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  api_key:
    secure: NjjFKL/HEGYUpbiDt1yl9EP4z/w7pc/rJpUkOm2PbyUQBHHdRozVdZ01U6xe2v3eoGXmBL7I0235KZbI0VZOukZ5X79vSjQKcheqIqMRgMQeNi8nWoSl5WFPc09TnBp73kt/EdRzARJbs3wWlrylgR6VYS1d0+tuEywb9uxwaiSUKb69C0IjXRF00H4IKZlZuT/NOQUF0KnpZ1reYQe4rwc2Mv0mo8vbvjmbmSoSGVWuwA9PEggjPYMd6hOuOOElSiFHMhsT3D6QzgGIF++lDG+kZUEEPwCJm2+7lGWBdfx4RbIAJkJy2o6q2dih0ODLhdclROlWqDYWRAvu+KKTF+eMbhQiOPgan9uNlJrB7J027QX+nIZ6/vf9fvqm1Pfx3wQ6eU0J4xdufmqd0MDRvjYm9QMyjqFP7sr5Wyswo1m2Kjo3L/c90uEP+FF42Bo2aPyN1QwjNLKuGSrFC4zsSipJzswX4FUklKftaohnalxsX6b3jQy8W10v2v38aI9+i0rr5BEdHj1v/lUu5vxjDs3J2JPsnZwhS/yjNNyEVJyN3IzUqKYwhLLfbyBe92yMMYKjhdoMBJiiLK2ND+mLUXKcgncMkZN/nhhNzKhDVf7FiFLJZZuqqRW9+1JQNGPFUNBSbdiKmKOs0ZKY7h/1QwCfycwdY3ykrXRkrsgnc9o=
app: josenvisa
true:
  repo: peeveepv/Quiz
  branch: master
