language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  api_key:
    secure: ITKsV9Sl54HfMwPk1BmkHzK88weDcOG/F1ee9T+u5ScsPNKHrhdqfpl2coXi4H5mhCc9XPon1BrgPU4gpgIlWgC6kj365ev7udbmYOvBNTdd00ps5M+uKrzWbtwng3QEtLb8E7pwGUCcMC/xizPhrBnIDE5bWqgPIlCuR8iMUyE/2dJW56nbZ/BVLv5LC9XnTY039qSY2D5kcP2syQG2fBql3BWHYsCRY+AgdGKL9Gsnlzm5mtOmDyUIguB200el2/3el/qAjTgohnmxh6BZlrsFmqgQY/s2hwuJhPwTVoiOACVLttKGz9vdW946LXKgbey2g6z5jOrCJ2SCBC88bs/058vwN6ZIkWT7uqD862vrhoxFb06KaO8MkTiJlRJ0pylQn+dkM4ziJspy0ON4FE8g/7eN+dZLvjDATKnn9I7gq0KD6QgrI84pWkwUDwR4F849uChCOoQ0YdKa/PburLUJxUWyRLH9yjINPKF134ftR4/jAn9MKdrn87D0fPzWnh4QyYMcd1pigm1p8vVuodivt8sdROShCmeFSbpu3DefNzGeR7g8ZwRSSEsKARJYK71LulhkumYL9wLPMZylfxQ3vKMGlrVbmlS/PwS/YkamJkLobIgVPRAMr1Pm2urqZOQITN/57sZXSsv+gcOX7Itno9ZOyUP2cd8cRPSe6uw=
app: visapeli
true:
  repo: peeveepv/Quiz
