language: node_js
node_js:
- 8.11.1
before_install:
- cd ./quiz-backend
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: R+EojVuqEizWs4c7tUPZFWPeSBC9R5faoqotZReItxuGcxXekTGlnSdTgTT8k5M7pgEUZFoJN4lA9LnTYzryNBj7hftGnJ76EUcHFsHwG9s7ocgAWShFWvjjlgXePXZbzE3LB/nd1NPEAZFfBFyjXBzVtrM3hpKPvs/8f4Xnu1NzVVooJq0+9acstXwxWmOUrhbfJYMrod4Qx6UXjl3ghF24QUVXOz2aG2wd/Lylrv/+2dZ3iPo0OcjmtYWJbAju5CU6S6ZAwfXr9C/LoepH7QigVJaTSA/RJ0/svWsEyfR3ymcJ1E7Kc+dFna0WDSN0HFhTmExNQUao5JzKbijhW9GZjiAUDdXhujo0zPAS1gH+KRPdYPfn2ykgUq5H+9d5ZXuR9xxbGYrG++dRor7zhsOfwbXUCz+UCf/F2au/Eq8mHlN9XoDYYHomN5rTRWaTL+UttnpjUFfI0VAzffHcsyDGPZr9tkAFOSIeIJ1rmKRJPtrocoGi+ZqKVRewg/1/9QpzTbqyZC4oUPx7q2DiklwmMz1VCsGd5QnLA3JS2azaHMvY1zlyuje4wDlxeQm7YY+InnJDMiEbyCvXJnNKZkWoBJekrZWzI6vWQ5RexhEmtxYSUjJzdK8dBSyCovf5c/3Cf8JkVClv1w28HlVpO5PorBKMfZ85qw0Q8If/DQY=
app: visapeli
true:
  repo: peeveepv/Quiz
